<<<<<<< HEAD
packages:
  - .
=======
>>>>>>> 9c69ceb712d475b9a9bd31fc9b787240061a05a5
allowBuilds:
  '@parcel/watcher': true
  unrs-resolver: true
  vue-demi: true
<<<<<<< HEAD
minimumReleaseAge: 0
=======
>>>>>>> 9c69ceb712d475b9a9bd31fc9b787240061a05a5
